import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  NavModule,
    CardModule,
    FormModule,
    GridModule,
    TabsModule,
    TableModule,
    ModalModule,
    ToastModule,
    BadgeModule,
    ButtonModule,
    AvatarModule,
    FooterModule,
    HeaderModule,
    SharedModule,
    TooltipModule,
    SpinnerModule,
    SidebarModule,
    CalloutModule,
    ProgressModule,
    DropdownModule,
    UtilitiesModule,
    ListGroupModule,
    BreadcrumbModule,
    ButtonGroupModule,
} from '@coreui/angular';

@NgModule({
  declarations: [],
  imports: [
    NavModule,
    CardModule,
    FormModule,
    GridModule,
    TabsModule,
    TableModule,
    ModalModule,
    ToastModule,
    BadgeModule,
    ButtonModule,
    CommonModule,
    AvatarModule,
    FooterModule,
    HeaderModule,
    SharedModule,
    TooltipModule,
    SpinnerModule,
    SidebarModule,
    CalloutModule,
    ProgressModule,
    DropdownModule,
    UtilitiesModule,
    ListGroupModule,
    BreadcrumbModule,
    ButtonGroupModule,
  ], 
  
  exports: [
    NavModule,
    CardModule,
    FormModule,
    GridModule,
    TabsModule,
    TableModule,
    ModalModule,
    ToastModule,
    BadgeModule,
    ButtonModule,
    CommonModule,
    AvatarModule,
    FooterModule,
    HeaderModule,
    SharedModule,
    TooltipModule,
    SpinnerModule,
    SidebarModule,
    CalloutModule,
    ProgressModule,
    DropdownModule,
    UtilitiesModule,
    ListGroupModule,
    BreadcrumbModule,
    ButtonGroupModule,
  ]
})
export class AngularCoreuiModule { }
